component: scf
name: bs_school
app: bs_school
stage: release

inputs:
  name: bs_school
  src:
    src: ./
    exclude:
      - .env
  type: web
  region: ap-guangzhou
  runtime: Nodejs12.16
  handler: index.main_handler
  memorySize: 64
  timeout: 128
  events:
    - apigw:
        parameters:
          protocols:
            - http
            - https
          environment: release
          endpoints:
            - path: /
              method: ANY
